stages:
  - build
  - docker-build
  - deploy

# react 빌드
react-build-job:
  stage: build
  image: node:20-alpine3.17
  script:
    - echo "Start building react app"
    - npm install
    - npm run build
    - echo "Build Successful"
  artifacts:
    - front-web/builds/

# 위에서 빌드된 react가 아닌 dockerfile을 이용하여 빌드
docker-build-job:
  stage: docker-build
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build . -t nginx-web-static:latest front-web/Dockerfile
    - docker push nginx-web-static:latest

# 도커 이미지로 서버 배포
deploy-app:
  stage: deploy
  before-script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull nginx-web-static:latest
  script:
    - docker run -d --name nginx-web-static nginx-web-static:latest